[[redirects]]
    from ="/*"
    to = "/*"
    status = 200


[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[dev]
  publish = "public"
  base
  functions = "functions"